group:
  # Common grouped files
  - files:
    - source: LICENSE.txt
      dest: LICENSE.txt
    - source: .gitignore
      dest: .gitignore
    - source: .editorconfig
      dest: .editorconfig
    - source: .gitattributes
      dest: .gitattributes
  - repos: |
      AdmiringWorm/test-label-repository
