group:
  # Common Files
  - files:
    - source: LICENSE.txt
      dest: LICENSE.txt
    - source: .gitignore
      dest: .gitignore
    - source: .editorconfig
      dest: .editorconfig
    - source: .gitattributes
      dest: .gitattributes
    repos: |
      AdmiringWorm/test-label-repository
      AdmiringWorm/test-templates
  - files:
    - source: .github/dest-workflows/
      dest: .github/workflows/
      deleteOrphaned: true
    - source: .build/csharp/
      dest: ./
      deleteOrphaned: true
      exclude: |
        recipe.cake
    - source: .build/csharp/recipe.cake
      dest: recipe.cake
    repos: |
      AdmiringWorm/test-templates
