group:
  # Common Files
  - files:
    - source: LICENSE.txt
      dest: LICENSE.txt
    - source: .gitignore
      dest: .gitignore
    - source: .editorconfig
      dest: .editorconfig
    - source: .gitattributes
      dest: .gitattributes
    repos: |
      AdmiringWorm/test-label-repository
      AdmiringWorm/test-templates
  - files:
    - source: .github/dest-workflows/
      dest: .github/workflows/
      deleteOrphaned: true
